/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"

#include "uart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	char msg[20];
	int i = 1;
	UsartInit(BAUD_9600);
	UsartPuts("Hello DESD @ Sunbeam!\r\n");
	UsartPuts("God Bless You!\r\n");
	UsartPuts("DESD Sep 2021!\r\n");
	while(1) {
		sprintf(msg, "Count = %d\r\n", i++);
		UsartPuts(msg);
		DelayMs(1000);
	}
	return 0;
}






